### ISSUE TITLE
Geliştirilebilir Bölümler

### ISSUE THREAD

**Issue by DursunCanPoyraz** [the-turk/flarum-pallet-theme#2]
Bu bildirim altında gördüğüm geliştirilebilir bölümleri paylaşacağım.

1. Sol üstten pin emojisi olan butona tıkladığımda görüntü resimdeki gibi bozuluyor.
![image](https://user-images.githubusercontent.com/74768208/122176325-24eaa480-ce8d-11eb-9c7f-a718bca2ce80.png)

2. Anasayfada sol kısımda Kullanıcı Listesi, Grup Listesi gibi uzantılar ile gelen butonlar gözükmüyor.
![image](https://user-images.githubusercontent.com/74768208/122176608-7b57e300-ce8d-11eb-950f-c5cd09574d94.png)

**Comment by the-turk** [comment]
1) Geçici çözüm olarak panelden eklenebilir:
```
.hasPane.panePinned .App-content, .hasPane.panePinned .App-footer {
	margin-left: 120px;
}
```
2) Diğer eklentiler sol menüyü tanımadığı için bu butonlarının tek tek eklenmesi gerekiyor. Yeni sürümde bu linkleri ekleyebilirim.

**Comment by DursunCanPoyraz** [comment]
İkinci bahsettiğim bölüm için ben hangi dosyalar üzerinden işlem yapabilirim?

**Comment by the-turk** [comment]
Her iki sorunun da çözüldüğü `0.1.0-beta.2` sürümünü yükleyebilirsin.

```
composer require "the-turk/flarum-pallet-theme:0.1.0-beta.2"
```

**Comment by DursunCanPoyraz** [comment]
Teşekkürler. Grup listesi ve kullanıcı listesini örnek olarak vermiştim. Aklıma geldikçe diğer butonları da buraya yazacağım. Ekleyebilir misiniz?

1. Özel Tartışmalar (https://discuss.flarum.org/d/4762-friendsofflarum-by-bu-well-integrated-advanced-private-discussions)
2. Kategoriler (https://discuss.flarum.org/d/23184-flarum-categories)

**Comment by the-turk** [comment]
```
composer require "the-turk/flarum-pallet-theme:0.1.0-beta.4"
```
