### ISSUE TITLE
davwheat Custom Side Nav Links

### ISSUE THREAD

**Issue by DursunCanPoyraz** [the-turk/flarum-pallet-theme#3]
davwheat Custom Side Nav Links uzantısı için temaya destek ekleyebilir misiniz?

https://discuss.flarum.org/d/26380-custom-side-nav-links

**Comment by the-turk** [comment]
Bu aynı eklentinin bu tema için tekrar yazılması anlamına geliyor, vaktim olursa böyle bir şeyi tema ayarlarına gömmeyi düşünebilirim ancak şu aralar söz vermem mümkün değil maalesef. Eklemek istediğin link için:

`vendor/the-turk/flarum-pallet-theme/js/src/forum/components/Sidebar.js` dosyasına gidip `items()` fonksiyonu içine (örneğin 185. satır) aşağıdaki gibi bir kod yazabilirsin:

```
items.add(
	'benim-adresim',
	<LinkButton icon="fas fa-comment" href="https://google.com">
	  Benim Adresim
	</LinkButton>,
	38
);
```

Daha sonra komut istemcisinden (örneğin `cmd`) `vendor/the-turk/flarum-pallet-theme/js` dizinine gidip sırasıyla `npm install` ve `npm run build` komutlarını çalıştırmalısın. Bu işlemlerden sonra yeni adresi sitedeki panelde görmen gerekiyor.

Bu yolun tek eksi yanı yeni bir güncellemede yaptığın değişikliklerin kaybolacak olmasıdır. Bu yüzden `Sidebar.js` dosyasına eklediğin kodların bir kopyasını saklamak isteyebilirsin.

**Comment by hacklido** [comment]
So this is done?
